### ISSUE TITLE
"self._addDefaultMeta is not a function" Can you help me with this error

### ISSUE THREAD

**Issue by blackcloud007** [Garlicvideos/reddits-nightmare#30] opened 2024-03-09 10:42 UTC
C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot>npm run start

> reddits-nightmare@2.0.0 start
> node beepboop.js

[3/9/2024, 4:08:41 PM] [Setup] Info: Prerequisites present, booting!
[3/9/2024, 4:08:52 PM] [Instagram] Info: Successfully logged in to Instagram!
[3/9/2024, 4:08:52 PM] [Instagram] Info: Uploading with a frequency of every 43200000ms
https://reddit.com/r/ProgrammerHumor/hot.json
C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\winston\lib\winston\create-logger.js:80
        self._addDefaultMeta(info);
             ^

TypeError: self._addDefaultMeta is not a function
    at DerivedLogger.<computed> (C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\winston\lib\winston\create-logger.js:80:14)
    at RedditListingWatcher.emit (node:events:513:28)
    at C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\reddit-snooper\watcher.js:137:42
    at Request._callback (C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\reddit-snooper\watcher.js:65:21)
    at self.callback (C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (C:\Users\kkarmegams\Desktop\Bot\Axiver\reddits-nightmare-3.0.0\bot\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Axiver** [comment] 2024-03-23 13:59
Hi, thanks for opening this issue. I've looked into this and identified the cause, will be implementing the fix in the next couple of days.

**Comment by Axiver** [comment] 2024-03-23 14:25
Hi, this has been fixed in the `master` branch.  Please obtain a updated copy of that branch.

This error was occurring because the `reddit-snooper` package that this project depends on was broken by the Reddit API changes that occurred a few months ago. As `reddit-snooper` is not being maintained by its original owner, I will need to fork it and work on a fix. This will take a long time.

As a result, the reddit snooping module of the bot has been disabled. You will need to manually place content into the `/assets/images/approved` folder for the bot to upload to Instagram automatically.

**Closed as completed** 2024-03-23 14:25 UTC
Labels: bug
